name: vr_club_app
description: "Сайт для администрирования VR клуба"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.0
  dio: ^5.0.0
  go_router: ^14.0.0
  flutter_svg: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
